services:
  backend:
    container_name: 'ai-adventure.api'
    image: 'ai-adventure.api'
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
     - "8000:8000"
     - "8001:8001"
    depends_on:
     - "db"
     - "ollama"

  db:
    container_name: 'ai-adventure.database'
    image: postgres:latest
    environment:
      - POSTGRES_DB=ai-adventure
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  
  ollama:
    container_name: 'ollama'
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - MODEL=llama3.2